version: '3.8'
services:
  stock-service-2:
    restart: always
    container_name: stock-service
    build: .
    ports:
      - 6200:3000
    environment:
      - DB_HOST=postgres-2
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_NAME=stock-service
    depends_on:
      - postgres-2
    links:
      - postgres-2
    command: sh -c 'yarn migration && yarn start'
  postgres-2:
    restart: always
    container_name: stock-serivce-db
    image: postgres:14.2-alpine
    ports:
      - 65432:5432
    volumes:
      - ~/apps/postgres/stock-service:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=stock-service
